"""empty message

Revision ID: 47e1393eeec5
Revises: 10eefbf4089b
Create Date: 2022-06-06 14:41:21.406360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e1393eeec5'
down_revision = '10eefbf4089b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('introduction', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'introduction')
    # ### end Alembic commands ###
