"""empty message

Revision ID: 971abf2d56e6
Revises: b1c0752737fa
Create Date: 2022-06-07 21:37:02.758522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971abf2d56e6'
down_revision = 'b1c0752737fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('song', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('song', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
