"""empty message

Revision ID: a07c821b1724
Revises: 
Create Date: 2022-06-05 16:28:35.135213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07c821b1724'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musician', sa.Column('e_mail', sa.String(length=120), nullable=True))
    op.add_column('musician', sa.Column('phone', sa.String(length=120), nullable=True))
    op.add_column('musician', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('musician', sa.Column('introduction', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('musician', 'introduction')
    op.drop_column('musician', 'website')
    op.drop_column('musician', 'phone')
    op.drop_column('musician', 'e_mail')
    # ### end Alembic commands ###
