"""empty message

Revision ID: b1c0752737fa
Revises: 47e1393eeec5
Create Date: 2022-06-06 19:07:40.798711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c0752737fa'
down_revision = '47e1393eeec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musician', sa.Column('avatar_link', sa.String(length=500), nullable=True))
    op.add_column('song', sa.Column('cover_link', sa.String(length=500), nullable=True))
    op.add_column('song', sa.Column('song_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'song_link')
    op.drop_column('song', 'cover_link')
    op.drop_column('musician', 'avatar_link')
    # ### end Alembic commands ###
