"""empty message

Revision ID: b4a4a1549fb7
Revises: 971abf2d56e6
Create Date: 2022-06-08 00:33:49.784846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a4a1549fb7'
down_revision = '971abf2d56e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre')
    op.add_column('musician', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('song', sa.Column('genre', sa.String(length=120), nullable=True))
    op.drop_constraint('song_genre_id_fkey', 'song', type_='foreignkey')
    op.drop_column('song', 'genre_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('song_genre_id_fkey', 'song', 'genre', ['genre_id'], ['id'])
    op.drop_column('song', 'genre')
    op.drop_column('musician', 'genres')
    op.create_table('genre',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='genre_pkey')
    )
    # ### end Alembic commands ###
